
from __future__ import annotations
from typing import Tuple
from pptx import Presentation
from pptx.util import Pt
from upe.doc_ast import Doc

def render_pptx(doc: Doc, out_path: str, slide_count_hint: int | None = None) -> None:
    prs = Presentation()
    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = doc.title
    slide.placeholders[1].text = "Generated by UPE"
    # Sections
    bullet_layout = prs.slide_layouts[1]
    for sec in doc.sections:
        slide = prs.slides.add_slide(bullet_layout)
        slide.shapes.title.text = sec.heading
        tf = slide.shapes.placeholders[1].text_frame
        tf.clear()
        for block in sec.blocks:
            if block.kind == "para":
                p = tf.add_paragraph()
                p.text = block.text
                p.font.size = Pt(18)
            elif block.kind == "list":
                for item in block.items:
                    p = tf.add_paragraph()
                    p.text = f"• {item}"
                    p.level = 1
    prs.save(out_path)
